import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, differenceInYears, parseISO } from 'date-fns';
import { Patient, Outcome, AppUser, AppState } from '../types';

export const generateClinicalReport = (
  patient: Patient,
  outcome: Outcome,
  state: AppState,
  lang: 'en' | 'es' = 'en'
) => {
  const doc = new jsPDF('p', 'pt', 'a4');
  
  const isEs = lang === 'es';
  const t = {
    clinicalPortal: isEs ? "PORTAL CLÍNICO" : "CLINICAL PORTAL",
    clinicalHistory: isEs ? "HISTORIA CLÍNICA DE EVOLUCIÓN" : "CLINICAL EVOLUTION HISTORY",
    reportId: isEs ? "ID Reporte" : "Report ID",
    generationDate: isEs ? "Fecha Generación" : "Generation Date",
    status: isEs ? "Estado" : "Status",
    completed: isEs ? "Completado" : "Completed",
    closed: isEs ? "Cerrado" : "Closed",
    generatedBy: isEs ? "Generado por Careways Connect - Plataforma de Soporte de Decisiones Clínicas" : "Generated by Careways Connect - Clinical Decision Support Platform",
    generatedOn: isEs ? "Generado el:" : "Generated on:",
    page: isEs ? "Página" : "Page",
    of: isEs ? "de" : "of",
    patientLbl: isEs ? "PACIENTE" : "PATIENT",
    idLbl: isEs ? "IDENTIFICACIÓN" : "ID",
    dobLbl: isEs ? "FECHA NACIMIENTO" : "DATE OF BIRTH",
    genderLbl: isEs ? "GÉNERO" : "GENDER",
    doctorLbl: isEs ? "MÉDICO TRATANTE" : "ATTENDING PHYSICIAN",
    weightLbl: isEs ? "PESO" : "WEIGHT",
    diagLbl: isEs ? "DIAGNÓSTICO PRINCIPAL" : "PRIMARY DIAGNOSIS",
    years: isEs ? "años" : "years",
    unknownPt: isEs ? "Paciente Desconocido" : "Unknown Patient",
    unknownUser: isEs ? "Usuario Desconocido" : "Unknown User",
    none: isEs ? "Ninguno" : "None",
    
    secPIM3: isEs ? "1. RESUMEN PIM3" : "1. PIM3 SUMMARY",
    score: "Score:",
    predMortality: isEs ? "Mortalidad Estimada:" : "Predicted Mortality:",
    riskCat: isEs ? "Categoría Riesgo:" : "Risk Category:",
    diagnosisSubtype: isEs ? "Subtipo de Diagnóstico:" : "Diagnosis Subtype:",
    dateTimeMeasured: isEs ? "Fecha/Hora de Medición:" : "Date/Time Measured:",
    lowRisk: isEs ? "Riesgo Bajo" : "Low Risk",
    modRisk: isEs ? "Riesgo Moderado" : "Moderate Risk",
    highRisk: isEs ? "Riesgo Alto" : "High Risk",
    specificRiskPresent: isEs ? "Diagnóstico Específico Presente" : "Specific Risk Diagnosis Present",
    standardBaseline: isEs ? "Línea Base Estándar" : "Standard Baseline",
    
    secVitals: isEs ? "2. SIGNOS VITALES (PRIMERA HORA UCI)" : "2. VITAL SIGNS (FIRST ICU HOUR)",
    valVariable: "Variable",
    valValue: isEs ? "Valor" : "Value",
    mechVent: isEs ? "Ventilación Mecánica" : "Mechanical Ventilation",
    pupilReact: isEs ? "Reactividad Pupilar" : "Pupillary Reactivity",
    yes: isEs ? "Sí" : "Yes",
    no: "No",
    reactive: isEs ? "Reactiva" : "Reactive",
    nonReactive: isEs ? "No Reactiva" : "Non-reactive",
    
    secAirway: isEs ? "3. MANEJO DE VÍA AÉREA" : "3. AIRWAY MANAGEMENT",
    valDetail: isEs ? "Detalle" : "Detail",
    intubated: isEs ? "Intubado" : "Intubated",
    intubDateTime: isEs ? "Fecha/Hora Intubación" : "Intubation Date/Time",
    tubeSize: isEs ? "Tamaño Tubo" : "Tube Size Used",
    tubeType: isEs ? "Tipo de Tubo" : "Tube Type",
    cuffed: isEs ? "Con Balón" : "Cuffed",
    uncuffed: isEs ? "Sin Balón" : "Uncuffed",
    tubePosition: isEs ? "Posición Tubo" : "Tube Position",
    tubePosVer: isEs ? "At Thoracic Inlet (Verified)" : "At Thoracic Inlet (Verified)", // Mock
    intubRoute: isEs ? "Ruta Intubación" : "Intubation Route",
    intubRouteVal: isEs ? "Orotraqueal" : "Orotracheal",
    intubator: isEs ? "Intubador" : "Intubator",
    intubatorVal: isEs ? "Intensivista" : "Intensivist",
    verMethods: isEs ? "Métodos de Verificación" : "Verification Methods",
    verMethodsVal: isEs ? "Capnografía, Auscultación" : "Capnography, Auscultation",
    attempts: isEs ? "Número de Intentos" : "Number of Attempts",
    complications: isEs ? "Complicaciones" : "Complications",
    accidentalExtubation: isEs ? "Extubación Accidental" : "Accidental Extubation",
    noneReported: isEs ? "Ninguna reportada" : "None reported",
    plannedExtubation: isEs ? "Extubación Electiva" : "Planned Extubation",
    
    secRisk: isEs ? "4. ESTRATIFICACIÓN DE RIESGO PIM3" : "4. RISK STRATIFICATION & PIM3 COMPONENTS",
    lowRiskDiag: isEs ? "Diagnóstico Riesgo Bajo" : "Low Risk Diagnosis",
    highRiskDiag: isEs ? "Diagnóstico Riesgo Alto" : "High Risk Diagnosis",
    vHighRiskDiag: isEs ? "Diagnóstico Riesgo Muy Alto" : "Very High Risk Diagnosis",
    electiveAdm: isEs ? "Admisión Electiva" : "Elective Admission",
    recoverySurg: isEs ? "Recuperación de Cirugía" : "Recovery From Surgery",
    
    secEvents: isEs ? "5. EVENTOS CRÍTICOS" : "5. CRITICAL EVENTS",
    dateTime: "Date/Time",
    eventType: isEs ? "Tipo de Evento" : "Event Type",
    description: isEs ? "Descripción" : "Description",
    actionsTaken: isEs ? "Acciones Tomadas" : "Actions Taken",
    icuAdmission: isEs ? "Admisión UCI" : "ICU Admission",
    icuAdmDesc: isEs ? "Ingreso de paciente a UCIP" : "Patient admitted to PICU",
    icuAdmAction: isEs ? "Evaluación inicial y estabilización" : "Initial assessment and stabilization",
    recEvents: isEs ? "Evento(s) registrado(s):" : "Recorded event(s):",
    cprInitiated: isEs ? "RCP iniciada, Reintubación" : "CPR initiated, Reintubation",
    reintubated: isEs ? "Reintubado" : "Reintubated",
    
    secMortality: isEs ? "6. DESENLACES" : "6. MORTALITY OUTCOMES",
    icuOutcome: isEs ? "Desenlace UCI" : "ICU Outcome",
    hospOutcome: isEs ? "Desenlace Hospitalario" : "Hospital Outcome",
    dischargeDate: isEs ? "Fecha de Egreso" : "Date of Discharge",
    survivalStatus: isEs ? "Estado Vital" : "Survival Status",
    discharged: isEs ? "Dado de Alta" : "Discharged",
    deceased: isEs ? "Fallecido" : "Deceased",
    living: isEs ? "Vivo" : "Living",
    
    secActivity: isEs ? "7. REGISTRO DE ACTIVIDAD CLÍNICA" : "7. CLINICAL ACTIVITY LOG",
    dateC: isEs ? "Fecha" : "Date",
    userC: isEs ? "Usuario" : "User",
    actionC: isEs ? "Acción" : "Action",
    pdfGen: isEs ? "Reporte PDF Generado" : "PDF Report Generated",
    caseRev: isEs ? "Caso Revisado" : "Case Reviewed",
    draftAuto: isEs ? "Borrador Autoguardado" : "Draft Auto-saved",
    admin: "Admin",
    
    secNarrative: isEs ? "8. REPORTE CLÍNICO NARRATIVO" : "8. NARRATIVE CLINICAL REPORT",
    narrativeTpl1: isEs ? "Paciente ingresado a UCIP en la fecha " : "Patient admitted to PICU on ",
    narrativeTpl2: isEs ? " con diagnóstico principal de " : " with a diagnosis of ",
    narrativeTpl3: isEs ? ". Las medidas fisiológicas iniciales reportaron Presión Arterial Sistólica de " : ". Initial physiological measurements demonstrated a systolic BP of ",
    narrativeTpl4: isEs ? " mmHg, PaO2 de " : " mmHg, PaO2 of ",
    narrativeTpl5: isEs ? " mmHg, y exceso de base de " : " mmHg, and a Base Excess of ",
    narrativeTpl6: isEs ? ". El paciente " : ". The patient ",
    narrativeTpl7: isEs ? "requirió" : "required",
    narrativeTpl8: isEs ? "no requirió" : "did not require",
    narrativeTpl9: isEs ? " ventilación mecánica durante la primera hora. Respuesta pupilar " : " mechanical ventilation within the first hour of admission. Pupillary response was noted as ",
    narrativeTpl10: isEs ? ". El score PIM3 calculado es de " : ". Total calculated PIM3 Score is ",
    narrativeTpl11: isEs ? ", indicando una probabilidad de mortalidad estimada del " : ", indicating an estimated mortality risk of "
  };

  // Careways Colors
  const primaryColor = [32, 64, 113]; // #204071
  const secondaryColor = [55, 150, 216]; // #3796D8
  const headerBgColor = [246, 251, 255]; // #F6FBFF
  
  const pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  const margin = 40;

  // Header Logo and Info
  const addHeader = (doc: jsPDF, isFirstPage: boolean) => {
    // Careways Logo placeholder (Blue Box with text)
    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.roundedRect(margin, margin, 40, 40, 4, 4, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("CW", margin + 10, margin + 26);

    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFontSize(14);
    doc.text(t.clinicalPortal, margin + 50, margin + 20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.text(t.clinicalHistory, margin + 50, margin + 35);

    // Right side info
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(9);
    doc.text(`${t.reportId}: #${patient.identifier || patient.mrn}`, pageWidth - margin, margin + 15, { align: 'right' });
    doc.text(`${t.generationDate}: ${format(new Date(), 'dd MMM yyyy, HH:mm')}`, pageWidth - margin, margin + 30, { align: 'right' });
    doc.text(`${t.status}: ${outcome.status === 'Living' ? t.completed : t.closed}`, pageWidth - margin, margin + 45, { align: 'right' });
  };

  // Footer Info
  const addFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(t.generatedBy, margin, pageHeight - margin);
    doc.text(`${t.generatedOn} ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, margin, pageHeight - margin + 12);
    
    doc.text(`${t.page} ${pageNumber} ${t.of} ${totalPages}`, pageWidth - margin, pageHeight - margin + 12, { align: 'right' });
  };

  // --- Start Content ---
  doc.setFont("helvetica");
  
  // Section 1: Patient Header Block
  let cursorY = 110;

  const rawName = patient.name || t.unknownPt;
  const splitName = doc.splitTextToSize(rawName, 130);
  const nameLinesHeight = splitName.length * 12;
  const secondRowY = cursorY + 35 + Math.max(nameLinesHeight, 14) + 10;
  
  const rawDiag = outcome.diagnosis || t.none;
  const splitDiag = doc.splitTextToSize(rawDiag, 230);
  const diagHeight = splitDiag.length * 12;

  const totalBoxHeight = (secondRowY - cursorY) + 15 + Math.max(diagHeight, 12) + 20;

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, cursorY, pageWidth - margin * 2, totalBoxHeight, 4, 4, 'FD');
  
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(t.patientLbl, margin + 15, cursorY + 20);
  doc.text(t.idLbl, margin + 160, cursorY + 20);
  doc.text(t.dobLbl, margin + 280, cursorY + 20);
  doc.text(t.genderLbl, margin + 420, cursorY + 20);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  const patientAge = patient.birthDate ? differenceInYears(new Date(), parseISO(patient.birthDate)) : 0;
  
  // Ensure we don't bleed into the next column too much if really long
  doc.text(splitName, margin + 15, cursorY + 35);

  doc.text(patient.mrn || 'N/A', margin + 160, cursorY + 35);
  doc.text(`${patient.birthDate ? format(parseISO(patient.birthDate), 'dd/MM/yyyy') : 'N/A'} (${patientAge} ${t.years})`, margin + 280, cursorY + 35);
  doc.text(patient.gender || 'N/A', margin + 420, cursorY + 35);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text(t.doctorLbl, margin + 15, secondRowY);
  doc.text(t.weightLbl, margin + 160, secondRowY);
  doc.text(t.diagLbl, margin + 280, secondRowY);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(state.currentUser ? state.currentUser.name : t.unknownUser, margin + 15, secondRowY + 15);
  doc.text(outcome.weight ? `${outcome.weight} kg` : 'N/A', margin + 160, secondRowY + 15);
  
  doc.text(splitDiag, margin + 280, secondRowY + 15);

  cursorY += totalBoxHeight + 20;

  // Common function for Section Header
  const sectionHeader = (title: string, yPos: number): number => {
    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.rect(margin, yPos, 4, 15, 'F');
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title.toUpperCase(), margin + 12, yPos + 12);
    return yPos + 30;
  };

  // Section 1: Resumen PIM3
  cursorY = sectionHeader(t.secPIM3, cursorY);
  
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  
  const riskCategory = (outcome.mortalityProbability || 0) < 10 ? t.lowRisk : (outcome.mortalityProbability || 0) < 30 ? t.modRisk : t.highRisk;
  const diagSubtype = outcome.pim3LowRiskDiagnosis || outcome.pim3HighRiskDiagnosis || outcome.pim3VeryHighRiskDiagnosis ? t.specificRiskPresent : t.standardBaseline;
  const measDateTime = patient.admissionDate ? format(parseISO(patient.admissionDate), 'dd/MM/yyyy HH:mm') : 'N/A';

  doc.setFont("helvetica", "bold");
  doc.text(t.score, margin + 15, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(outcome.pim3Score?.toString() || '0', margin + 120, cursorY);

  doc.setFont("helvetica", "bold");
  doc.text(t.predMortality, margin + 15, cursorY + 16);
  doc.setFont("helvetica", "normal");
  doc.text(`${outcome.mortalityProbability || 0} %`, margin + 160, cursorY + 16);

  doc.setFont("helvetica", "bold");
  doc.text(t.riskCat, margin + 15, cursorY + 32);
  doc.setFont("helvetica", "normal");
  doc.text(riskCategory, margin + 120, cursorY + 32);
  
  doc.setFont("helvetica", "bold");
  doc.text(t.diagLbl + ":", margin + 15, cursorY + 48);
  doc.setFont("helvetica", "normal");
  doc.text(outcome.diagnosis || t.none, margin + 160, cursorY + 48);

  doc.setFont("helvetica", "bold");
  doc.text(t.diagnosisSubtype, margin + 15, cursorY + 64);
  doc.setFont("helvetica", "normal");
  doc.text(diagSubtype, margin + 160, cursorY + 64);

  doc.setFont("helvetica", "bold");
  doc.text(t.dateTimeMeasured, margin + 15, cursorY + 80);
  doc.setFont("helvetica", "normal");
  doc.text(measDateTime, margin + 160, cursorY + 80);

  cursorY += 105;

  // Section 5: First ICU Hour / PIM3
  cursorY = sectionHeader(t.secVitals, cursorY);
  
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.valVariable, t.valValue]],
    body: [
      ['Systolic BP (mmHg)', outcome.systolicBP?.toString() || '--'],
      ['FiO2 (%)', outcome.fiO2?.toString() || '--'],
      ['PaO2 (mmHg)', outcome.paO2?.toString() || '--'],
      ['Base Excess', outcome.baseExcess?.toString() || '--'],
      [t.mechVent, outcome.mechanicalVentilation ? t.yes : t.no],
      [t.pupilReact, outcome.pupils === 1 ? t.reactive : t.nonReactive]
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Airway Management
  cursorY = sectionHeader(t.secAirway, cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.valVariable, t.valDetail]],
    body: [
      [t.intubated, outcome.intubated === 1 ? t.yes : t.no],
      [t.intubDateTime, outcome.intubationDateTime ? format(new Date(outcome.intubationDateTime), 'dd/MM/yyyy HH:mm') : 'N/A'],
      [t.tubeSize, outcome.ettSize ? `${outcome.ettSize} mm` : 'N/A'],
      [t.tubeType, outcome.ettCuffed ? t.cuffed : t.uncuffed],
      [t.tubePosition, t.tubePosVer], // Mock
      [t.intubRoute, t.intubRouteVal], // Mock
      [t.intubator, t.intubatorVal], // Mock
      [t.verMethods, t.verMethodsVal], // Mock
      [t.attempts, '1'], // Mock
      [t.complications, outcome.accidentalExtubation === 1 ? t.accidentalExtubation : t.noneReported],
      [t.plannedExtubation, outcome.electiveExtubation ? t.yes : t.no],
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Additional sections: Risk Stratification
  cursorY = sectionHeader(t.secRisk, cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.valVariable, t.valValue]],
    body: [
      [t.riskCat, riskCategory],
      [t.lowRiskDiag, outcome.pim3LowRiskDiagnosis ? t.yes : t.no],
      [t.highRiskDiag, outcome.pim3HighRiskDiagnosis ? t.yes : t.no],
      [t.vHighRiskDiag, outcome.pim3VeryHighRiskDiagnosis ? t.yes : t.no],
      [t.electiveAdm, outcome.electiveAdmission ? t.yes : t.no],
      [t.recoverySurg, outcome.surgeryRecovery ? t.yes : t.no],
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Critical Events
  cursorY = sectionHeader(t.secEvents, cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.dateTime, t.eventType, t.description, t.actionsTaken]],
    body: [
      [
        format(new Date(patient.admissionDate || new Date()), 'dd/MM/yyyy HH:mm'),
        t.icuAdmission,
        t.icuAdmDesc,
        t.icuAdmAction
      ],
      ...(outcome.accidentalExtubation === 1 ? [[
        format(new Date(), 'dd/MM/yyyy HH:mm'),
        t.accidentalExtubation,
        `${t.recEvents} ${outcome.accidentalExtubationCount || 1}`,
        outcome.requiedCprPostAccidental ? t.cprInitiated : t.reintubated
      ]] : [])
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Mortality Outcomes
  cursorY = sectionHeader(t.secMortality, cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.icuOutcome, t.hospOutcome, t.dischargeDate, t.survivalStatus]],
    body: [
      [
        outcome.status === 'Living' ? t.discharged : t.deceased,
        outcome.status === 'Living' ? t.discharged : t.deceased,
        patient.dischargeDate ? format(parseISO(patient.dischargeDate), 'dd/MM/yyyy') : 'N/A',
        outcome.status === 'Living' ? t.living : t.deceased
      ]
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Clinical Activity Log
  cursorY = sectionHeader(t.secActivity, cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [[t.dateC, t.userC, t.actionC]],
    body: [
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || t.admin, t.pdfGen],
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || t.admin, t.caseRev],
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || t.admin, t.draftAuto]
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Narrative Clinical Report
  cursorY = sectionHeader(t.secNarrative, cursorY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);
  const narrative = `${t.narrativeTpl1}${patient.admissionDate || 'N/A'}${t.narrativeTpl2}${outcome.diagnosis || t.none}${t.narrativeTpl3}${outcome.systolicBP || '--'}${t.narrativeTpl4}${outcome.paO2 || '--'}${t.narrativeTpl5}${outcome.baseExcess || '--'}${t.narrativeTpl6}${outcome.mechanicalVentilation ? t.narrativeTpl7 : t.narrativeTpl8}${t.narrativeTpl9}${outcome.pupils === 1 ? t.reactive : t.nonReactive}${t.narrativeTpl10}${outcome.pim3Score || 0}${t.narrativeTpl11}${outcome.mortalityProbability || 0}%.`;
  
  const narrativeLines = doc.splitTextToSize(narrative, pageWidth - margin * 2);
  doc.text(narrativeLines, margin, cursorY);
  
  cursorY += narrativeLines.length * 12 + 20;

  // Add Headers & Footers to all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i === 1) addHeader(doc, true);
    // Draw line separating footer
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - margin - 5, pageWidth - margin, pageHeight - margin - 5);
    addFooter(doc, i, totalPages);
  }

  // Save the PDF
  doc.save(`Clinical_Report_${patient.mrn}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
