import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, differenceInYears, parseISO } from 'date-fns';
import { Patient, Outcome, AppUser, AppState } from '../types';

export const generateClinicalReport = (
  patient: Patient,
  outcome: Outcome,
  state: AppState
) => {
  const doc = new jsPDF('p', 'pt', 'a4');
  
  // Careways Colors
  const primaryColor = [32, 64, 113]; // #204071
  const secondaryColor = [55, 150, 216]; // #3796D8
  const headerBgColor = [246, 251, 255]; // #F6FBFF
  
  const pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  const margin = 40;

  // Header Logo and Info
  const addHeader = (doc: jsPDF, isFirstPage: boolean) => {
    // Careways Logo placeholder (Blue Box with text)
    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.roundedRect(margin, margin, 40, 40, 4, 4, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("CW", margin + 10, margin + 26);

    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFontSize(14);
    doc.text("CLINICAL PORTAL", margin + 50, margin + 20);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.text("HISTORIA CLÍNICA DE EVOLUCIÓN", margin + 50, margin + 35);

    // Right side info
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(9);
    doc.text(`ID Reporte: #${patient.identifier || patient.mrn}`, pageWidth - margin, margin + 15, { align: 'right' });
    doc.text(`Fecha Generación: ${format(new Date(), 'dd MMM yyyy, HH:mm')}`, pageWidth - margin, margin + 30, { align: 'right' });
    doc.text(`Estado: ${outcome.status === 'Living' ? 'Completed' : 'Closed'}`, pageWidth - margin, margin + 45, { align: 'right' });
  };

  // Footer Info
  const addFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    const text1 = "Generated by Careways Connect - Clinical Decision Support Platform";
    doc.text(text1, margin, pageHeight - margin);
    const text2 = `Generated on: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`;
    doc.text(text2, margin, pageHeight - margin + 12);
    
    const text3 = `Página ${pageNumber} de ${totalPages}`;
    doc.text(text3, pageWidth - margin, pageHeight - margin + 12, { align: 'right' });
  };

  // --- Start Content ---
  doc.setFont("helvetica");
  
  // Section 1: Patient Header Block
  let cursorY = 110;
  
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, cursorY, pageWidth - margin * 2, 80, 4, 4, 'FD');
  
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("PACIENTE", margin + 15, cursorY + 20);
  doc.text("IDENTIFICACIÓN", margin + 160, cursorY + 20);
  doc.text("FECHA NACIMIENTO", margin + 280, cursorY + 20);
  doc.text("GÉNERO", margin + 420, cursorY + 20);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  const patientAge = patient.birthDate ? differenceInYears(new Date(), parseISO(patient.birthDate)) : 0;
  doc.text(patient.name || 'Unknown Patient', margin + 15, cursorY + 35);
  doc.text(patient.mrn || 'N/A', margin + 160, cursorY + 35);
  doc.text(`${patient.birthDate ? format(parseISO(patient.birthDate), 'dd/MM/yyyy') : 'N/A'} (${patientAge} años)`, margin + 280, cursorY + 35);
  doc.text(patient.gender || 'N/A', margin + 420, cursorY + 35);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text("MÉDICO TRATANTE", margin + 15, cursorY + 60);
  doc.text("PESO", margin + 160, cursorY + 60);
  doc.text("DIAGNÓSTICO PRINCIPAL", margin + 280, cursorY + 60);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(state.currentUser ? state.currentUser.name : 'Unknown User', margin + 15, cursorY + 75);
  doc.text(outcome.weight ? `${outcome.weight} kg` : 'N/A', margin + 160, cursorY + 75);
  doc.text(outcome.diagnosis || 'None', margin + 280, cursorY + 75);

  cursorY += 100;

  // Common function for Section Header
  const sectionHeader = (title: string, yPos: number): number => {
    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.rect(margin, yPos, 4, 15, 'F');
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title.toUpperCase(), margin + 12, yPos + 12);
    return yPos + 30;
  };

  // Section 1: Resumen PIM3
  cursorY = sectionHeader("1. RESUMEN PIM3", cursorY);
  
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  
  const riskCategory = (outcome.mortalityProbability || 0) < 10 ? 'Low Risk' : (outcome.mortalityProbability || 0) < 30 ? 'Moderate Risk' : 'High Risk';
  const diagSubtype = outcome.pim3LowRiskDiagnosis || outcome.pim3HighRiskDiagnosis || outcome.pim3VeryHighRiskDiagnosis ? 'Specific Risk Diagnosis Present' : 'Standard Baseline';
  const measDateTime = patient.admissionDate ? format(parseISO(patient.admissionDate), 'dd/MM/yyyy HH:mm') : 'N/A';

  doc.setFont("helvetica", "bold");
  doc.text("Score:", margin + 15, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(outcome.pim3Score?.toString() || '0', margin + 120, cursorY);

  doc.setFont("helvetica", "bold");
  doc.text("Predicted Mortality:", margin + 15, cursorY + 16);
  doc.setFont("helvetica", "normal");
  doc.text(`${outcome.mortalityProbability || 0} %`, margin + 120, cursorY + 16);

  doc.setFont("helvetica", "bold");
  doc.text("Risk Category:", margin + 15, cursorY + 32);
  doc.setFont("helvetica", "normal");
  doc.text(riskCategory, margin + 120, cursorY + 32);
  
  doc.setFont("helvetica", "bold");
  doc.text("Diagnosis:", margin + 15, cursorY + 48);
  doc.setFont("helvetica", "normal");
  doc.text(outcome.diagnosis || 'None', margin + 120, cursorY + 48);

  doc.setFont("helvetica", "bold");
  doc.text("Diagnosis Subtype:", margin + 15, cursorY + 64);
  doc.setFont("helvetica", "normal");
  doc.text(diagSubtype, margin + 120, cursorY + 64);

  doc.setFont("helvetica", "bold");
  doc.text("Date/Time Measured:", margin + 15, cursorY + 80);
  doc.setFont("helvetica", "normal");
  doc.text(measDateTime, margin + 130, cursorY + 80);

  cursorY += 105;

  // Section 5: First ICU Hour / PIM3
  cursorY = sectionHeader("2. SIGNOS VITALES (FIRST ICU HOUR)", cursorY);
  
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['Variable', 'Valor']],
    body: [
      ['Systolic BP (mmHg)', outcome.systolicBP?.toString() || '--'],
      ['FiO₂ (%)', outcome.fiO2?.toString() || '--'],
      ['PaO₂ (mmHg)', outcome.paO2?.toString() || '--'],
      ['Base Excess', outcome.baseExcess?.toString() || '--'],
      ['Mechanical Ventilation', outcome.mechanicalVentilation ? 'Yes' : 'No'],
      ['Pupillary Reactivity', outcome.pupils === 1 ? 'Reactive' : 'Non-reactive']
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Airway Management
  cursorY = sectionHeader("3. AIRWAY MANAGEMENT", cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['Variable', 'Detalle']],
    body: [
      ['Intubated', outcome.intubated === 1 ? 'Yes' : 'No'],
      ['Intubation Date/Time', outcome.intubationDateTime ? format(new Date(outcome.intubationDateTime), 'dd/MM/yyyy HH:mm') : 'N/A'],
      ['Tube Size Used', outcome.ettSize ? `${outcome.ettSize} mm` : 'N/A'],
      ['Tube Type', outcome.ettCuffed ? 'Cuffed' : 'Uncuffed'],
      ['Tube Position', 'At Thoracic Inlet (Verified)'], // Mock
      ['Intubation Route', 'Orotracheal'], // Mock
      ['Intubator', 'Intensivist'], // Mock
      ['Verification Methods', 'Capnography, Auscultation'], // Mock
      ['Number of Attempts', '1'], // Mock
      ['Complications', outcome.accidentalExtubation === 1 ? 'Accidental Extubation' : 'None reported'],
      ['Planned Extubation', outcome.electiveExtubation ? 'Yes' : 'No'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Additional sections: Risk Stratification
  cursorY = sectionHeader("4. RISK STRATIFICATION & PIM3 COMPONENTS", cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['Variable', 'Value']],
    body: [
      ['Risk Category', (outcome.mortalityProbability || 0) < 10 ? 'Low Risk' : (outcome.mortalityProbability || 0) < 30 ? 'Moderate Risk' : 'High Risk'],
      ['Low Risk Diagnosis', outcome.pim3LowRiskDiagnosis ? 'Yes' : 'No'],
      ['High Risk Diagnosis', outcome.pim3HighRiskDiagnosis ? 'Yes' : 'No'],
      ['Very High Risk Diagnosis', outcome.pim3VeryHighRiskDiagnosis ? 'Yes' : 'No'],
      ['Elective Admission', outcome.electiveAdmission ? 'Yes' : 'No'],
      ['Recovery From Surgery', outcome.surgeryRecovery ? 'Yes' : 'No'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Critical Events
  cursorY = sectionHeader("5. CRITICAL EVENTS", cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['Date/Time', 'Event Type', 'Description', 'Actions Taken']],
    body: [
      [
        format(new Date(patient.admissionDate || new Date()), 'dd/MM/yyyy HH:mm'),
        'ICU Admission',
        'Patient admitted to PICU',
        'Initial assessment and stabilization'
      ],
      ...(outcome.accidentalExtubation === 1 ? [[
        format(new Date(), 'dd/MM/yyyy HH:mm'),
        'Accidental Extubation',
        `Recorded ${outcome.accidentalExtubationCount || 1} event(s)`,
        outcome.requiedCprPostAccidental ? 'CPR initiated, Reintubation' : 'Reintubated'
      ]] : [])
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Mortality Outcomes
  cursorY = sectionHeader("6. MORTALITY OUTCOMES", cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['ICU Outcome', 'Hospital Outcome', 'Date of Discharge', 'Survival Status']],
    body: [
      [
        outcome.status === 'Living' ? 'Discharged' : 'Deceased',
        outcome.status === 'Living' ? 'Discharged' : 'Deceased',
        patient.dischargeDate ? format(parseISO(patient.dischargeDate), 'dd/MM/yyyy') : 'N/A',
        outcome.status === 'Living' ? 'Living' : 'Deceased'
      ]
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Clinical Activity Log
  cursorY = sectionHeader("7. CLINICAL ACTIVITY LOG", cursorY);
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [['Date', 'User', 'Action']],
    body: [
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || 'Admin', 'PDF Report Generated'],
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || 'Admin', 'Case Reviewed'],
      [format(new Date(), 'dd-MMM-yyyy HH:mm'), state.currentUser?.name || 'Admin', 'Draft Auto-saved']
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: primaryColor, fontStyle: 'bold' },
    styles: { fontSize: 9 }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 25;

  // Narrative Clinical Report
  cursorY = sectionHeader("8. NARRATIVE CLINICAL REPORT", cursorY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);
  const narrative = `Patient admitted to PICU on ${patient.admissionDate || 'unknown date'} with a diagnosis of ${outcome.diagnosis || 'unspecified'}. Initial physiological measurements demonstrated a systolic BP of ${outcome.systolicBP || '--'} mmHg, PaO2 of ${outcome.paO2 || '--'} mmHg, and a Base Excess of ${outcome.baseExcess || '--'}. The patient ${outcome.mechanicalVentilation ? 'required' : 'did not require'} mechanical ventilation within the first hour of admission. Pupillary response was noted as ${outcome.pupils === 1 ? 'reactive' : 'non-reactive'}. Total calculated PIM3 Score is ${outcome.pim3Score || 0}, indicating a ${outcome.mortalityProbability || 0}% estimated risk of mortality.`;
  
  const narrativeLines = doc.splitTextToSize(narrative, pageWidth - margin * 2);
  doc.text(narrativeLines, margin, cursorY);
  
  cursorY += narrativeLines.length * 12 + 20;

  // Add Headers & Footers to all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i === 1) addHeader(doc, true);
    // Draw line separating footer
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - margin - 5, pageWidth - margin, pageHeight - margin - 5);
    addFooter(doc, i, totalPages);
  }

  // Save the PDF
  doc.save(`Clinical_Report_${patient.mrn}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
